var level2x ='{"bricks":[{"brickRow": [{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdBlue"},{"x": 0,"y": 0,"status": 1,"color": "grdYellow"},{"x": 0,"y": 0,"status": 1,"color": "grdGreen"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"}]},{' +
    '"brickRow": [{"x": 0,"y": 0,"status": 0,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"}]},{' +
    '"brickRow": [{"x": 0,"y": 0,"status": 0,"color": "grdYellow"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"}]},{' +
    '"brickRow": [{"x": 0,"y": 0,"status": 0,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"}]},{' +
    '"brickRow": [{"x": 0,"y": 0,"status": 0,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"}]},{' +
    '"brickRow": [{"x": 0,"y": 0,"status": 0,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"}]},{' +
    '"brickRow": [{"x": 0,"y": 0,"status": 0,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"}]},{' +

    '"brickRow": [{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"}]},{' +
    '"brickRow": [{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"}]},{' +

    '"brickRow": [{"x": 0,"y": 0,"status": 0,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"}]},{' +
    '"brickRow": [{"x": 0,"y": 0,"status": 0,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"}]},{' +
    '"brickRow": [{"x": 0,"y": 0,"status": 0,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"}]},{' +
    '"brickRow": [{"x": 0,"y": 0,"status": 0,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"}]},{' +
    '"brickRow": [{"x": 0,"y": 0,"status": 0,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"}]},{' +
    '"brickRow": [{"x": 0,"y": 0,"status": 0,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"}]},{' +
    '"brickRow": [{"x": 0,"y": 0,"status": 0,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"},{"x": 0,"y": 0,"status": 1,"color": "grdRed"}]}' +
    ']}';
